import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import MainCard from '../components/mainCard'

export default function Home() {
  const [products, setProducts] = useState([])

  // on load get products
  useEffect(() => {
    fetch('https://fakestoreapi.com/products')
        .then(response => response.json())
        .then(response => setProducts(response))
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Clothing Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainImageContainer}>
        <div className={styles.mainImage}>
          <img src = '/static/images/mainImage.jpg' alt = "Main Image" />
        </div>
      </div>

      <div className={styles.mainTextBox}>
        <h1>NEXT Store</h1>
        <p>NEXT Store, Inc. is an Australian multinational corporation that is engaged in the design, development, manufacturing, and worldwide marketing and sales of footwear, apparel, equipment, accessories, and services.</p>
      </div>

      <div className={styles.mainTextBox}>
        <h2>Recent Products</h2>
        <div className={styles.productGrid}>
          {products.slice(0, 4).map((product) => {return <div>
            <MainCard product={product} />
          </div>})}
        </div>
      </div>

      <div className={styles.mainTextBox}>
        <h1>Join Us</h1>
        <p>Become a member of NEXT store and receive notification and discounts</p>
        <button className = {styles.button}>Become a Member</button>
        <img className={styles.footerImage} src = '/static/images/footerImage.jpg' alt = "Footer Image" />
      </div>

    </div>
  )
}
